//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XIVLogger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XIVLogger.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord:.
        /// </summary>
        internal static string AboutDiscord {
            get {
                return ResourceManager.GetString("AboutDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Thread.
        /// </summary>
        internal static string ButtonDiscord {
            get {
                return ResourceManager.GetString("ButtonDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string ButtonIssues {
            get {
                return ResourceManager.GetString("ButtonIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ko-Fi Tip.
        /// </summary>
        internal static string ButtonKoFi {
            get {
                return ResourceManager.GetString("ButtonKoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string ButtonSaveClipboard {
            get {
                return ResourceManager.GetString("ButtonSaveClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Config.
        /// </summary>
        internal static string ButtonSaveConfig {
            get {
                return ResourceManager.GetString("ButtonSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        internal static string ButtonSaveLog {
            get {
                return ResourceManager.GetString("ButtonSaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosaved chat log to {0}..
        /// </summary>
        internal static string ChatMessageAutosave {
            get {
                return ResourceManager.GetString("ChatMessageAutosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat log copied to clipboard..
        /// </summary>
        internal static string ChatMessageCopy {
            get {
                return ResourceManager.GetString("ChatMessageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} messages copied to clipboard..
        /// </summary>
        internal static string ChatMessageCopyNumber {
            get {
                return ResourceManager.GetString("ChatMessageCopyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat log saved at {0}..
        /// </summary>
        internal static string ChatMessageLastCopy {
            get {
                return ResourceManager.GetString("ChatMessageLastCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} messages saved at {1}..
        /// </summary>
        internal static string ChatMessageLastCopyNumber {
            get {
                return ResourceManager.GetString("ChatMessageLastCopyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string ChatTypeAlliance {
            get {
                return ResourceManager.GetString("ChatTypeAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CWLS.
        /// </summary>
        internal static string ChatTypeCWLS {
            get {
                return ResourceManager.GetString("ChatTypeCWLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBG.
        /// </summary>
        internal static string ChatTypeDBG {
            get {
                return ResourceManager.GetString("ChatTypeDBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        internal static string ChatTypeEmote {
            get {
                return ResourceManager.GetString("ChatTypeEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC.
        /// </summary>
        internal static string ChatTypeFC {
            get {
                return ResourceManager.GetString("ChatTypeFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        internal static string ChatTypeLS {
            get {
                return ResourceManager.GetString("ChatTypeLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NN.
        /// </summary>
        internal static string ChatTypeNN {
            get {
                return ResourceManager.GetString("ChatTypeNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string ChatTypeParty {
            get {
                return ResourceManager.GetString("ChatTypeParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PvP.
        /// </summary>
        internal static string ChatTypePvP {
            get {
                return ResourceManager.GetString("ChatTypePvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string ChatTypeSay {
            get {
                return ResourceManager.GetString("ChatTypeSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string ChatTypeShout {
            get {
                return ResourceManager.GetString("ChatTypeShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string ChatTypeYell {
            get {
                return ResourceManager.GetString("ChatTypeYell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        internal static string FullNameAlliance {
            get {
                return ResourceManager.GetString("FullNameAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Emotes.
        /// </summary>
        internal static string FullNameCustomEmote {
            get {
                return ResourceManager.GetString("FullNameCustomEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Linkshell.
        /// </summary>
        internal static string FullNameCWLS {
            get {
                return ResourceManager.GetString("FullNameCWLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross World Party.
        /// </summary>
        internal static string FullNameCWParty {
            get {
                return ResourceManager.GetString("FullNameCWParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string FullNameDebug {
            get {
                return ResourceManager.GetString("FullNameDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo (Some System Messages).
        /// </summary>
        internal static string FullNameEcho {
            get {
                return ResourceManager.GetString("FullNameEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Emotes.
        /// </summary>
        internal static string FullNameEmote {
            get {
                return ResourceManager.GetString("FullNameEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Company.
        /// </summary>
        internal static string FullNameFC {
            get {
                return ResourceManager.GetString("FullNameFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Incoming.
        /// </summary>
        internal static string FullNameInTell {
            get {
                return ResourceManager.GetString("FullNameInTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell.
        /// </summary>
        internal static string FullNameLS {
            get {
                return ResourceManager.GetString("FullNameLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice Network.
        /// </summary>
        internal static string FullNameNN {
            get {
                return ResourceManager.GetString("FullNameNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string FullNameNotice {
            get {
                return ResourceManager.GetString("FullNameNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other /random.
        /// </summary>
        internal static string FullNameOtherRandom {
            get {
                return ResourceManager.GetString("FullNameOtherRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Outgoing.
        /// </summary>
        internal static string FullNameOutTell {
            get {
                return ResourceManager.GetString("FullNameOutTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string FullNameParty {
            get {
                return ResourceManager.GetString("FullNameParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVP Team.
        /// </summary>
        internal static string FullNamePvP {
            get {
                return ResourceManager.GetString("FullNamePvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string FullNameSay {
            get {
                return ResourceManager.GetString("FullNameSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string FullNameShout {
            get {
                return ResourceManager.GetString("FullNameShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string FullNameSystemError {
            get {
                return ResourceManager.GetString("FullNameSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Messages.
        /// </summary>
        internal static string FullNameSystemMessage {
            get {
                return ResourceManager.GetString("FullNameSystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yell.
        /// </summary>
        internal static string FullNameYell {
            get {
                return ResourceManager.GetString("FullNameYell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your /random.
        /// </summary>
        internal static string FullNameYourRandom {
            get {
                return ResourceManager.GetString("FullNameYourRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Config.
        /// </summary>
        internal static string NewConfigChatConfig {
            get {
                return ResourceManager.GetString("NewConfigChatConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Name:.
        /// </summary>
        internal static string NewConfigName {
            get {
                return ResourceManager.GetString("NewConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config selected....
        /// </summary>
        internal static string NewConfigNotSelected {
            get {
                return ResourceManager.GetString("NewConfigNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Active Chat Configuration.
        /// </summary>
        internal static string NewConfigSetActive {
            get {
                return ResourceManager.GetString("NewConfigSetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log copied to clipboard.
        /// </summary>
        internal static string NotificationLogCopy {
            get {
                return ResourceManager.GetString("NotificationLogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log saved at {0}.
        /// </summary>
        internal static string NotificationLogSaved {
            get {
                return ResourceManager.GetString("NotificationLogSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string TabAdvanced {
            get {
                return ResourceManager.GetString("TabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        internal static string TabAdvancedActive {
            get {
                return ResourceManager.GetString("TabAdvancedActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Name.
        /// </summary>
        internal static string TabAdvancedConfigName {
            get {
                return ResourceManager.GetString("TabAdvancedConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TabAdvancedEdit {
            get {
                return ResourceManager.GetString("TabAdvancedEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Config.
        /// </summary>
        internal static string TabAdvancedNewConfigName {
            get {
                return ResourceManager.GetString("TabAdvancedNewConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TabAdvancedRemove {
            get {
                return ResourceManager.GetString("TabAdvancedRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up additional configurations with different combinations of chat types here..
        /// </summary>
        internal static string TabAdvancedTooltip {
            get {
                return ResourceManager.GetString("TabAdvancedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Types.
        /// </summary>
        internal static string TabChatTypes {
            get {
                return ResourceManager.GetString("TabChatTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default configuration settings.
        /// </summary>
        internal static string TabChatTypesTooltip {
            get {
                return ResourceManager.GetString("TabChatTypesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave.
        /// </summary>
        internal static string TabSettingsAutosave {
            get {
                return ResourceManager.GetString("TabSettingsAutosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave notification echoed in chat?.
        /// </summary>
        internal static string TabSettingsAutosaveNotification {
            get {
                return ResourceManager.GetString("TabSettingsAutosaveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autosave File Path:.
        /// </summary>
        internal static string TabSettingsAutosavePath {
            get {
                return ResourceManager.GetString("TabSettingsAutosavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string TabSettingsEvery {
            get {
                return ResourceManager.GetString("TabSettingsEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        internal static string TabSettingsFileName {
            get {
                return ResourceManager.GetString("TabSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path:.
        /// </summary>
        internal static string TabSettingsFilePath {
            get {
                return ResourceManager.GetString("TabSettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore chat types.
        /// </summary>
        internal static string TabSettingsIgnoreChatTypes {
            get {
                return ResourceManager.GetString("TabSettingsIgnoreChatTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all chat messages, no matter the chat type it belongs to..
        /// </summary>
        internal static string TabSettingsIgnoreChatTypesTooltip {
            get {
                return ResourceManager.GetString("TabSettingsIgnoreChatTypesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include datestamp.
        /// </summary>
        internal static string TabSettingsIncludeTimestamp {
            get {
                return ResourceManager.GetString("TabSettingsIncludeTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string TabSettingsMinutes {
            get {
                return ResourceManager.GetString("TabSettingsMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: Documents folder.
        /// </summary>
        internal static string TabSettingsPathTooltip {
            get {
                return ResourceManager.GetString("TabSettingsPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        internal static string TabSettingsShowSeconds {
            get {
                return ResourceManager.GetString("TabSettingsShowSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate sortable filenames.
        /// </summary>
        internal static string TabSettingsSortableFilenames {
            get {
                return ResourceManager.GetString("TabSettingsSortableFilenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include timestamp.
        /// </summary>
        internal static string TabSettingsTimestamp {
            get {
                return ResourceManager.GetString("TabSettingsTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 24h time.
        /// </summary>
        internal static string TabSettingsUse24h {
            get {
                return ResourceManager.GetString("TabSettingsUse24h", resourceCulture);
            }
        }
    }
}
